name: Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
        
      - name: Build
        run: hugo
        working-directory: 

      - name: Deploy to public repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: terrymight/dipbits-technology-ltd-public
          publish_branch: main
          publish_dir: ./public
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
